version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - carbonplaceholder
ignoreWords:
  - devided
  - более
  - добавляет
  - изменился
  - инициализилизирует
  - коллекции
  - маршруты
  - наши
  - считываем
  - флагом
import: []
